### PR TITLE
Issues #8 #9 #10 resolved

### LINKED ISSUE #8: No check for date of leaving and returning
**Actual Behaviour**

Currently, there is no error thrown if the date of leaving is after date of return.

**Expected Behaviour**

The user should be prompted to check the dates if he selects a date of return before date of leaving.

**Screenshots of the issue**

In the following screenshot, date of leaving is Dec 15 while date of return is Dec14, which is incorrect. Hence, this needs to be handled properly.

screenshot 2018-12-05 at 1 17 18 pm

### PR DESCRIPTION
**Pull request by 091karan**
Fixes #8

Changes: Added an if statement to check validation of date of leaving and returning.

### CODE REVIEW

**Comment by 091karan** [comment]
Fixes #9 

Changes - Leave application fields are made mandatory.

**Comment by 091karan** [comment]
Fixes #10: Add a section for adding comments.

Changes: Comment adding section is added at the 'leave_details' page.

**Comment by agarwalrounak** [comment]
Hey @091karan, when you are working on a issue please comment there to let others know.

**Comment by 091karan** [comment]
@agarwalrounak Okay. Sure.

**Comment by arundhatigupta** [comment]
Hey @091karan , thank you for your contribution. I would like to suggest a few things, which you need to work upon before we can finalise this PR:
- Always fix one issue per PR and not multiple issues in one PR.
- Always follow the PR template and add screenshots before and after whenever you make any change related to UI.
- Please read this [doc](https://chris.beams.io/posts/git-commit/) to understand how to write a good commit message and try to implement the same here.
I hope to see these changes implemented so that we can finalise and merge this PR. 😃

**Comment by arundhatigupta** [comment]
@091karan To help you, here's an example: Suppose you worked on issue #10 . Then, a good commit message could be "feat: Add section for adding comments". 
Also, please solve one issue in this PR. As I can see, you have sent this PR from the development branch of your fork. I would suggest creating a new branch with base branch as development and commit your changes on that new branch. Then open a PR from your new branch, rather than the development branch of your fork, to the development branch of the main repository. That way you will be able to work upon multiple issues at a time. That's the beauty of a VCS! 😃 
For now, you can 'cherry-pick' other commits and add them to a new branch. And, update those branches accordingly and send PR from them. As the issues #8 , #9 and #10 are unrelated i.e. do not require a lot of changes in same files or same lines, hence there won't be conflicts. So, that way you would not have to spend a lot of time working again on those issues and it will also help us keep a clean commit history with one issue per PR. In case, you are not familiar with any of the terms, feel free to drop in a comment, will try to help you out. But, before that please try reading Git documentation and online resources. Try to Google the terms that I mentioned above. I hope that helps. :)

**Comment by 091karan** [comment]
Hi @arundhati24 . I am a newbie to open source and GitHub. That's why I couldn't follow you at the first place. I did checked the online resources which cleared a lot of doubts, but I am still unsure of sending the PRs from separate branches. My approach for the above mess is - 

- Creating a branch(branch1), removing the contents of two commits(possibly #9 and #8) and opening a PR from this branch to the development branch of NJACKWinterOfCode/online_leave_management_iitp repository.

- Adding contents of #9 issue to this branch(branch1) and again opening a PR, or creating a new branch(brach2) with base branch as "branch1" and opening a PR.

- Repeating the above step for the #8.

- Or closing this PR and starting a fresh for all the commits.

I don't think if I am making any sense or not, still can you please help me out?
Thanks.

**Comment by arundhatigupta** [comment]
Yes, I could understand that. I too faced this issue when I started working with Git. But, keep going! :)
So, for now, to prevent you from getting confused, I would suggest you close this PR and send a new one. To proceed, checkout the development branch, 'reset the head' to the latest commit on the 'upstream' development branch (not your fork). Next, 'fetch' and 'rebase' your branch on the 'upstream' development branch. Now, 'checkout' a new branch. Work on one issue. 'Commit' your changes and 'push' to your fork and then open a 'pull request' to the development branch of the main repository.
For each issue, make a new branch and repeat the process.
I suggest you note the terms that I have highlighted and read about them before proceeding.

**Pull request closed without merging**
