### PR TITLE
Adds screenshots to README.md

### LINKED ISSUE #11: Add screenshots of the project to README.md
**Actual Behaviour**

Currently, there are no screenshots of the project in README.md.

**Expected Behaviour**

Add upto 6 screenshots in README.md.

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes #11 

Changes: Screenshots of the projects were added to [README.md](../blob/development/README.md)

Screenshots for the change: 
- Before
screenshot from 2018-12-06 17-39-56

- After
screenshot from 2018-12-06 17-41-53
screenshot from 2018-12-06 17-42-30
screenshot from 2018-12-06 17-42-52
screenshot from 2018-12-06 17-43-22

### CODE REVIEW

**Comment by arundhatigupta** [comment]
@agarwalrounak It would be great if you could please add screenshots for the changes you've made.
That way I would be able to see the changes and review them better. :)

**Comment by agarwalrounak** [comment]
Done. Please review!

**Comment by arundhatigupta** [comment]
Good work @agarwalrounak . Almost there, just two additions needed:
- Add two more screenshots - one of pending leaves and one past leaves screen. Try to add screenshots showing at least 4 pending and at least 3 past leaves. (You can easily make them :) )
- Try to add the screenshots in a table format. 2 screenshots on each row and keep the login screen before the sign up screen. For an example, you can check [this](https://github.com/fossasia/susi_android/blob/development/README.md) README.md. You can see how the table has been added. In this README.md there are three screenshots per row, but we need just two.

**Comment by agarwalrounak** [comment]
How to make past leaves?

**Comment by arundhatigupta** [comment]
You need to create a superuser.
Next, sign up for two 'Authority' accounts - one would play the role of a 'Faculty Advisor' and the other would be 'Warden'. Now, login to the admin panel. There, you need to create a leave approving faculty and a leave approving warden. In actual project also, this would be done by the administrator only. In practice, for every batch (year of joining) and programme and branch there would be a faculty advisor, but for testing purposes, you can make one case. Suppose you have a student account for year 2016. So, for testing, create a leave approving faculty and associate it with 2016 batch (you will see the fields when you login to admin). Similarly, create a leave approving warden. Note that the warden does not belong to any batch. Rather, you simply need to choose the hostel type. Once, you have created these accounts, apply for a leave from student account. Then, logout and login to faculty advisor's account. There, in the pending leaves, you'll see the leave application sent from the student account. Approve it. Now, this would appear in the pending leaves section of the warden (depends the student lives in girls hostel or boys hostel, notification is sent accordingly). Now, approve/reject the leave from there. This leave will appear in the past leaves of the warden account. Now, when you login to the student account again, this leave would appear in the past leaves of the student.

**Comment by 27vinayvyas** [comment]
Hello Ma'am @arundhati24 
I just wanted to ask if this stuff done or not ?
If its still needed , i can try this out once.
Thnx in advance

**Comment by agarwalrounak** [comment]
@27vinayvyas I was working on this issue but you can take it up now. 
I already have a PR #19 pending for review for issue #18 . I have tried pinging @arundhati24 but there seems to be no reply from her side.

**Comment by 27vinayvyas** [comment]
@agarwalrounak 
Bro do u know of some other project in here with somewhat same required skills(like django, python and related stuff) , if yes then please let me know.

**Comment by agarwalrounak** [comment]
You can check on the [projects](https://njackwinterofcode.github.io/projects.html) page.

**Pull request merged**
